stages:
    - check-env
    - build
    - test 
    - deploy

variables:
    IMAGE_TAG: $CI_PIPELINE_ID-$CI_COMMIT_SHORT_SHA
    IMAGE_URL: $DOCKER_REG_URL/$CI_PROJECT_PATH

var-check:
    stage: check-env
    image:
        name: alpine:3.16.0
        entrypoint: [""]
    script:
        - echo "reg ====== $DOCKER_REG_URL"
        - echo "image tag == $IMAGE_TAG"
        - echo "image url == $IMAGE_URL"
        - echo "dag repo === $DAG_REPO"

build:
    image:
        name: $DOCKER_REG_URL/kaniko:debug
        entrypoint: [""]
    stage: build
    only:
        refs:
            - master
    script:
        - echo build and push image $IMAGE_URL:$IMAGE_TAG
        - echo "build and push new image:"
        - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile
            --insecure --skip-tls-verify --destination $IMAGE_URL:$IMAGE_TAG

push-dag:
    stage: deploy
    image:
        name: $DOCKER_REG_URL/infra/dagger:2.2.9
        entrypoint: [""]
    only:
        refs:
            - master
    before_script:
        - DAGS=$PWD/dags/
        - dagger --image $IMAGE_URL:$IMAGE_TAG --pattern $CI_PROJECT_URL --hash $CI_PROJECT_URL $DAGS/*
    script:
        - echo "update dag repo:"
        - cd /tmp
        - git clone $DAG_REPO
        - cd dags
        - mkdir -p $CI_PROJECT_PATH/$CI_COMMIT_BRANCH
        - rm -rf $CI_PROJECT_PATH/$CI_COMMIT_BRANCH
        - mkdir -p $CI_PROJECT_PATH/$CI_COMMIT_BRANCH
        - cp $DAGS/* $CI_PROJECT_PATH/$CI_COMMIT_BRANCH
        - git add $CI_PROJECT_PATH/$CI_COMMIT_BRANCH
        - git config user.email "cicd@yourcompany.com"
        - git config user.name "cicd"
        - git commit -m "update image for dags related to $CI_PROJECT_NAME"
        - git push

